[env:esp32]
platform = espressif32
board = lolin32
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM3
upload_protocol = esptool
build_flags = 
    -DARDUINO_LOOP_STACK_SIZE=8192
    -std=gnu++17
lib_deps = 
    ArduinoJson@^6.21.2
    ESP Async WebServer@^1.2.3
    AsyncTCP@^1.1.1
    SPIFFS
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.3.1
    someweisguy/esp_dmx@^4.1.0
board_build.partitions = default.csv
