[env:esp32]
platform = espressif32
board = lolin_d32
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM7
upload_protocol = esptool
build_flags = 
    -DARDUINO_LOOP_STACK_SIZE=8192
    -std=gnu++17
    -DUSER_SETUP_LOADED=1
    -DST7735_DRIVER=1
    -DTFT_WIDTH=80
    -DTFT_HEIGHT=160
    -DST7735_GREENTAB160x80
    -DTFT_MOSI=23
    -DTFT_SCLK=22
    -DTFT_CS=5
    -DTFT_DC=17
    -DTFT_RST=4
    -DSPI_FREQUENCY=27000000
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
lib_deps = 
    ArduinoJson@^6.21.2
    ESP Async WebServer@^1.2.3
    AsyncTCP@^1.1.1
    SPIFFS
    bodmer/TFT_eSPI@^2.5.0
    someweisguy/esp_dmx@^4.1.0
    kosme/arduinoFFT@^2.0.2
board_build.partitions = default.csv
